run:
  timeout: 5m

linters:
  enable:
    - gofumpt
    - gocritic
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
