name: go-cli CI

on:
  push:
    branches: [main]
    paths:
      - 'go-cli/**'
      - '.github/workflows/go-cli.yml'
      - '.github/workflows/go-ci.yml'
  pull_request:
    paths:
      - 'go-cli/**'
      - '.github/workflows/go-cli.yml'
      - '.github/workflows/go-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/go-ci.yml
    with:
      working-directory: go-cli
      test-paths: "./internal/..."
