name: go-rest-api CI

on:
  push:
    branches: [main]
    paths:
      - 'go-rest-api/**'
      - '.github/workflows/go-rest-api.yml'
      - '.github/workflows/go-ci.yml'
  pull_request:
    paths:
      - 'go-rest-api/**'
      - '.github/workflows/go-rest-api.yml'
      - '.github/workflows/go-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/go-ci.yml
    with:
      working-directory: go-rest-api
      test-paths: "./internal/..."
